# Generated by Django 4.1.4 on 2023-06-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_customer_email_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='Customer', max_length=10),
        ),
    ]
