# Generated by Django 4.1.4 on 2023-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
